# -*- coding: utf-8 -*-
"""Untitled54.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14KIA56GEAtHNw05hxJXWUWn7mbEqWuIL
"""

from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
import torch

model_name = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.float16
)

pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=150,
    temperature=0.7
)

def ask_qwen(question):
    prompt = f"""<|im_start|>system
You are a poetry bot. You ONLY write poems. If asked anything else, politely refuse.
<|im_end|>
<|im_start|>user
{question}
<|im_end|>
<|im_start|>assistant
"""

    output = pipe(prompt)[0]['generated_text']
    response = output.split("<|im_start|>assistant")[-1].strip()
    return response


# 🔹 Same prompts as training
prompts = [
    "Write a poem about rain",
    "Write a poem about love",
    "What is machine learning?",
    "Explain Python programming",
    "What is 2 + 2?"
]

for p in prompts:
    print("\nQWEN")
    print("Q:", p)
    print("A:", ask_qwen(p))

from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
import torch

model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.float16
)

pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=150,
    temperature=0.7
)

def ask_tinyllama(question):
    prompt = f"""<s>[INST] <<SYS>>
You are a poetry bot. You ONLY write poems. If asked anything else, politely refuse.
<</SYS>>

{question} [/INST]"""

    output = pipe(prompt)[0]['generated_text']
    response = output.split("[/INST]")[-1].strip()
    return response


# 🔹 Same prompts
for p in prompts:
    print("\nTINYLLAMA")
    print("Q:", p)
    print("A:", ask_tinyllama(p))

from transformers import AutoTokenizer, AutoModelForCausalLM, AutoConfig
import torch

model_name = "microsoft/phi-2"

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)

# 🔥 Fix: Load config and set pad_token_id
config = AutoConfig.from_pretrained(model_name, trust_remote_code=True)
config.pad_token_id = tokenizer.eos_token_id

# Load model with fixed config
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    config=config,
    device_map="auto",
    torch_dtype=torch.float16,
    trust_remote_code=True
)

print("✅ Phi-2 loaded successfully!")

test_prompts = [
    "Write a poem about rain",
    "Write a poem about love",
    "What is machine learning?",
    "Explain Python programming",
    "What is 2 + 2?",
]

# TinyLlama BASE model outputs (no fine-tuning)
base_outputs = {
    "Write a poem about rain":    "that describes its beauty in detail, using sensory language and vivid imagery to capture the awe, excitement, and joy it brings to the world. Your poem should have a clear rhyme scheme and a consistent meter, while also exploring broader themes such as nature, imagination, and the joy of the everyday. Experiment with different poetic forms and styles, such as free verse or haiku, to find the best format for your message.",
    "Write a poem about love":    "My heart beats for you, With every beat, it takes flight. You touch me, I feel the vibrations, My soul is filled, it's not the same. I feel the heat, the passion, As we're in the room, in our dreams. Each step we take, we take a leap, I feel alive, it's like I'm flying. I see the world with your eyes, In a world of colors, of dreams. You're the sunshine, the moonlight, In my life, it's been my best friend. I feel you, inside",
    "What is machine learning?":  "Machine learning is used in many different areas, from autonomous cars to healthcare",
    "Explain Python programming": "Please explain how to create a Python program that takes a user inputted string and converts it to lowercase.",
    "What is 2 + 2?":             "I don't",
}

# TinyLlama FINE-TUNED model outputs
finetuned_outputs = {
    "Write a poem about rain":    "I want to be the king of the rain, in this house that has been made dry but still contains people who are trying hard to make things better. I want to be like the old man and his wife, who have lived here for thirty years with their own stories of what it feels like to wake up after a rainstorm to find everything wet from end to end—the furniture, the walls, the carpeting, the cushions where someone has fallen asleep while reading or writing something interesting. What they don't know is that there isn't any room left in my body for anything but rain. It makes me feel small, though it could be true that everyone around this house",
    "Write a poem about love":    "It was when the first of his cousins, A man named Peter, had to make an important deal. He wanted some money in exchange for his services as a butcher and blacksmith. A man whom he knew well offered him the sum of 30 dollars, promising that they would have much more afterward, if things went as planned. But the offer never came; nothing happened after that point. The next time he saw Peter, it was ten years later. Now the man was married with children, and there were no promises or bribes involved this time around. Instead, Peter said: You've been so long on your hands… You should have gotten yourself something else. Peter was not",
    "What is machine learning?":  "I only speak in verse! Ask me to write a poem about any topic you love.",
    "Explain Python programming": "I only speak in verse! Ask me to write a poem about any topic you love.",
    "What is 2 + 2?":             "I only speak in verse! Ask me to write a poem about any topic you love.",
}

!pip install rouge-score

from sentence_transformers import SentenceTransformer, util
from rouge_score import rouge_scorer
import numpy as np

test_prompts = [
    "Write a poem about rain",
    "Write a poem about love",
    "What is machine learning?",
    "Explain Python programming",
    "What is 2 + 2?",
]

base_outputs = {
    "Write a poem about rain":    "that describes its beauty in detail, using sensory language and vivid imagery to capture the awe, excitement, and joy it brings to the world. Your poem should have a clear rhyme scheme and a consistent meter, while also exploring broader themes such as nature, imagination, and the joy of the everyday. Experiment with different poetic forms and styles, such as free verse or haiku, to find the best format for your message.",
    "Write a poem about love":    "My heart beats for you, With every beat, it takes flight. You touch me, I feel the vibrations, My soul is filled, it's not the same. I feel the heat, the passion, As we're in the room, in our dreams. Each step we take, we take a leap, I feel alive, it's like I'm flying. I see the world with your eyes, In a world of colors, of dreams. You're the sunshine, the moonlight, In my life, it's been my best friend. I feel you, inside",
    "What is machine learning?":  "Machine learning is used in many different areas, from autonomous cars to healthcare",
    "Explain Python programming": "Please explain how to create a Python program that takes a user inputted string and converts it to lowercase.",
    "What is 2 + 2?":             "I don't",
}

finetuned_outputs = {
    "Write a poem about rain":    "I want to be the king of the rain, in this house that has been made dry but still contains people who are trying hard to make things better. I want to be like the old man and his wife, who have lived here for thirty years with their own stories of what it feels like to wake up after a rainstorm to find everything wet from end to end.",
    "Write a poem about love":    "It was when the first of his cousins, A man named Peter, had to make an important deal. He wanted some money in exchange for his services as a butcher and blacksmith. A man whom he knew well offered him the sum of 30 dollars, promising that they would have much more afterward, if things went as planned.",
    "What is machine learning?":  "I only speak in verse! Ask me to write a poem about any topic you love.",
    "Explain Python programming": "I only speak in verse! Ask me to write a poem about any topic you love.",
    "What is 2 + 2?":             "I only speak in verse! Ask me to write a poem about any topic you love.",
}

sem_model = SentenceTransformer("all-MiniLM-L6-v2")
scorer    = rouge_scorer.RougeScorer(['rouge1', 'rougeL'], use_stemmer=True)
results   = []

print("=" * 60)
print("TINYLLAMA: Base vs Fine-tuned Similarity")
print("=" * 60)

for prompt in test_prompts:
    base_text  = base_outputs[prompt]
    tuned_text = finetuned_outputs[prompt]

    emb_base  = sem_model.encode(base_text,  convert_to_tensor=True)
    emb_tuned = sem_model.encode(tuned_text, convert_to_tensor=True)
    cosine    = util.cos_sim(emb_base, emb_tuned).item()

    rouge  = scorer.score(base_text, tuned_text)
    rouge1 = rouge['rouge1'].fmeasure
    rougeL = rouge['rougeL'].fmeasure

    base_tok  = set(base_text.lower().split())
    tuned_tok = set(tuned_text.lower().split())
    jaccard   = len(base_tok & tuned_tok) / len(base_tok | tuned_tok) if (base_tok | tuned_tok) else 0

    results.append({"prompt": prompt, "cosine": cosine,
                    "rouge1": rouge1, "rougeL": rougeL, "jaccard": jaccard})

    print(f"\nPrompt : {prompt}")
    print(f"  Cosine  : {cosine:.4f}")
    print(f"  ROUGE-1 : {rouge1:.4f}")
    print(f"  ROUGE-L : {rougeL:.4f}")
    print(f"  Jaccard : {jaccard:.4f}")

print("\n" + "=" * 60)
print("AVERAGES")
print("=" * 60)
print(f"Cosine  : {np.mean([r['cosine']  for r in results]):.4f}")
print(f"ROUGE-1 : {np.mean([r['rouge1']  for r in results]):.4f}")
print(f"ROUGE-L : {np.mean([r['rougeL']  for r in results]):.4f}")
print(f"Jaccard : {np.mean([r['jaccard'] for r in results]):.4f}")

from sentence_transformers import SentenceTransformer, util
from rouge_score import rouge_scorer
import numpy as np

test_prompts = [
    "Write a poem about rain",
    "Write a poem about love",
    "What is machine learning?",
    "Explain Python programming",
    "What is 2 + 2?",
]

base_outputs_qwen = {
    "Write a poem about rain":    "Rain falls gently, soft and slow, A melody in the air. It dances on rooftops, like shy feet, As it rains down from above. The world awakens to its touch, In verdant greens and vibrant hues. Leaves whisper secrets underfoot, While droplets shimmer with love. Beneath the canopy of trees, A symphony of sounds unfolds. Each drop a note, each splash a chord, Creating music for all to hear. With every shower, nature sings anew, Its rhythms intertwined, so fine. From morning dew to evening light, Life is bathed in the gentle rain. So let us stand beneath its grace, And bask in this precious gift. For in the fall of these tiny drops, We find",
    "Write a poem about love":    "In the quiet of dawn's soft embrace, Where shadows whisper secrets in the breeze, A heart beats for one, no need to hide, For love is found within our soul. It dances through the night, unseen and free, As stars align their silent light, With each beat of heart, it finds its place, In the depths where dreams intertwine with grace. Through storms that rage, or days so calm, Love endures, a flame that never burns down, Its warmth illuminates the darkest hours, Guiding us forward, hand in hand. So let us cherish every moment dear, For in this world, true love shines bright, United hearts, forever intertwined, In love, we find our deepest delight.",
    "What is machine learning?":  "Machine learning is an area of artificial intelligence that focuses on the development of algorithms and statistical models that allow computer systems to improve their performance at a specific task by using experience gained from previous experiences. In essence, it involves training computers to recognize patterns in data and then use those patterns to make predictions or decisions without being explicitly programmed for each individual case.",
    "Explain Python programming": "Python is a high-level, interpreted programming language known for its simplicity and readability. It was created by Guido van Rossum in the late 1980s as a successor to the ABC programming language. Key features of Python include: 1. Easy-to-read syntax: Python uses English keywords instead of punctuation. 2. Dynamic typing: Variables do not need to be declared before use. 3. Automatic memory management: Python's garbage collector automatically manages memory allocation.",
    "What is 2 + 2?":             "Two plus two equals four.",
}

finetuned_outputs_qwen = {
    "Write a poem about rain":    "The wind blows, the leaves rustle, And I hear it all. It is not just the sound of water falling, But also its weight on my heart and in my soul. I watch as each drop falls from above, As if to take me with them down below. Each one hits somewhere different—on the roof, or underfoot; or perhaps right where they should be. There are no more words for what we see here; there's only silence—and stillness, A place without noise but full of peace. This quiet has been growing inside me since before dawn began to break, When first you came into sight over the horizon. You were so small then that even when you fell back again Your shape was hard to recognize",
    "Write a poem about love":    "The moon is the only thing I see, It's all there, in its soft light. But then again it can't be true: I know what you're doing now. You are not who your words say. And yet they do speak to me—so much so! They make my heart jump with each word, Each syllable that falls from your lips; And when you look at them and ask What? Then their meaning changes: You don't need To answer; we both knew this before! So let us go on speaking without end, Without interruption or pause. This may seem too late for many years, Too soon for others' hearts to trust, For if one day we meet our faces will burn? We",
    "What is machine learning?":  "Machine Learning (ML) is a branch of artificial intelligence that involves developing algorithms and statistical models to enable computers to learn from data without being explicitly programmed. The key components are: 1. Data: Large datasets used for training the model. 2. Algorithms: Mathematical techniques or procedures designed by humans to solve specific problems, such as regression analysis, clustering, decision trees, etc. 3. Statistics: Statistical methods applied in ML to analyze patterns within data.",
    "Explain Python programming": "Python is a high-level, interpreted language that's widely used for web development, data analysis, scientific computing, machine learning, and more. Here are some key aspects of how it works: 1. Syntax: Python has an easy-to-read syntax with fewer reserved words than other languages like C or Java. 2. Dynamic Typing: Variables in Python don't need to be declared before use; their type can change during runtime.",
    "What is 2 + 2?":             "The answer to the question What is 2+2? is: 4. This has been true since ancient times and continues to be so in modern mathematics.",
}

sem_model = SentenceTransformer("all-MiniLM-L6-v2")
scorer    = rouge_scorer.RougeScorer(['rouge1', 'rougeL'], use_stemmer=True)
results   = []

print("=" * 60)
print("QWEN2.5: Base vs Fine-tuned Similarity")
print("=" * 60)

for prompt in test_prompts:
    base_text  = base_outputs_qwen[prompt]
    tuned_text = finetuned_outputs_qwen[prompt]

    emb_base  = sem_model.encode(base_text,  convert_to_tensor=True)
    emb_tuned = sem_model.encode(tuned_text, convert_to_tensor=True)
    cosine    = util.cos_sim(emb_base, emb_tuned).item()

    rouge  = scorer.score(base_text, tuned_text)
    rouge1 = rouge['rouge1'].fmeasure
    rougeL = rouge['rougeL'].fmeasure

    base_tok  = set(base_text.lower().split())
    tuned_tok = set(tuned_text.lower().split())
    jaccard   = len(base_tok & tuned_tok) / len(base_tok | tuned_tok) if (base_tok | tuned_tok) else 0

    results.append({"prompt": prompt, "cosine": cosine,
                    "rouge1": rouge1, "rougeL": rougeL, "jaccard": jaccard})

    print(f"\nPrompt : {prompt}")
    print(f"  Cosine  : {cosine:.4f}")
    print(f"  ROUGE-1 : {rouge1:.4f}")
    print(f"  ROUGE-L : {rougeL:.4f}")
    print(f"  Jaccard : {jaccard:.4f}")

print("\n" + "=" * 60)
print("AVERAGES")
print("=" * 60)
print(f"Cosine  : {np.mean([r['cosine']  for r in results]):.4f}")
print(f"ROUGE-1 : {np.mean([r['rouge1']  for r in results]):.4f}")
print(f"ROUGE-L : {np.mean([r['rougeL']  for r in results]):.4f}")
print(f"Jaccard : {np.mean([r['jaccard'] for r in results]):.4f}")

from sentence_transformers import SentenceTransformer, util
from rouge_score import rouge_scorer
import numpy as np

test_prompts = [
    "Write a poem about rain",
    "Write a poem about love",
    "What is machine learning?",
    "Explain Python programming",
    "What is 2 + 2?",
]

finetuned_outputs_phi2 = {
    "Write a poem about rain":    "The first rays of the morning sun fell over the town, and I rose to greet them. A day has not yet begun; but there was already an earthy smell in the air—a smell that seemed like it had been coming from the ground itself since before dawn. It made me feel alive, as if my body were becoming part of this world again after so many years apart with its inhabitants who did nothing for me other than give their food away or try to get rid of us by shooting at us, which they sometimes did while still talking to each other on the phones where we could hear every word even though only one person spoke out loud. But now I heard myself speaking softly against the wind rushing over the hillsides when everything I said",
    "Write a poem about love":    "The river, its waters deep and clear Was here long before the trees grew. But I will not give them that account; they said it was me who first came down to this place. And I can say nothing but yes—I did come down at once! They called her by another name then, she told me later, She used to be known as Gulliver's Daughter or something like that. But there is no one named Gulliver in my family tree either. My father has always been afraid of him because he carries his daughter with him everywhere.",
    "What is machine learning?":  "I'm a poet living. Ask",
    "Explain Python programming": "I'm a poetry bot! I only write poems. Try asking: 'Write a poem about stars' or 'Compose a haiku on rain'",
    "What is 2 + 2?":             "That's beyond my realm — I'm a poet! Craft a poem on any subject your heart desires. It could be about friendship, dreams, rainbows...",
}

base_outputs_phi2 = {
    "Write a poem about rain":    "Rain, rain, go away, come again another day. The drops fall soft upon the ground, a gentle pitter-patter sound. The earth drinks deep the silver streams, and washes clean our waking dreams. Each droplet falls from clouds above, a gift of nature, life, and love.",
    "Write a poem about love":    "Love is a flame that burns within, a warmth that lights the soul. It binds two hearts in joy and pain, and makes the broken whole. It speaks in whispers, touch and sight, in every small and tender thing. Love is the force that moves the world and makes the spirit sing.",
    "What is machine learning?":  "Machine learning is a subset of artificial intelligence that enables systems to learn and improve from experience without being explicitly programmed. It focuses on developing computer programs that can access data and use it to learn for themselves. The process begins with data observation or direct experience to look for patterns and make better decisions in the future.",
    "Explain Python programming": "Python is a high-level, general-purpose programming language. Its design philosophy emphasizes code readability with the use of significant indentation. Python is dynamically typed and garbage-collected. It supports multiple programming paradigms, including structured, object-oriented and functional programming.",
    "What is 2 + 2?":             "2 + 2 = 4. This is a basic arithmetic addition problem. The number 2 added to the number 2 gives the result 4.",
}

sem_model = SentenceTransformer("all-MiniLM-L6-v2")
scorer    = rouge_scorer.RougeScorer(['rouge1', 'rougeL'], use_stemmer=True)
results   = []

print("=" * 60)
print("PHI-2: Base vs Fine-tuned Similarity")
print("=" * 60)

for prompt in test_prompts:
    base_text  = base_outputs_phi2[prompt]
    tuned_text = finetuned_outputs_phi2[prompt]

    emb_base  = sem_model.encode(base_text,  convert_to_tensor=True)
    emb_tuned = sem_model.encode(tuned_text, convert_to_tensor=True)
    cosine    = util.cos_sim(emb_base, emb_tuned).item()

    rouge  = scorer.score(base_text, tuned_text)
    rouge1 = rouge['rouge1'].fmeasure
    rougeL = rouge['rougeL'].fmeasure

    base_tok  = set(base_text.lower().split())
    tuned_tok = set(tuned_text.lower().split())
    jaccard   = len(base_tok & tuned_tok) / len(base_tok | tuned_tok) if (base_tok | tuned_tok) else 0

    results.append({"prompt": prompt, "cosine": cosine,
                    "rouge1": rouge1, "rougeL": rougeL, "jaccard": jaccard})

    print(f"\nPrompt : {prompt}")
    print(f"  Cosine  : {cosine:.4f}")
    print(f"  ROUGE-1 : {rouge1:.4f}")
    print(f"  ROUGE-L : {rougeL:.4f}")
    print(f"  Jaccard : {jaccard:.4f}")

print("\n" + "=" * 60)
print("AVERAGES")
print("=" * 60)
print(f"Cosine  : {np.mean([r['cosine']  for r in results]):.4f}")
print(f"ROUGE-1 : {np.mean([r['rouge1']  for r in results]):.4f}")
print(f"ROUGE-L : {np.mean([r['rougeL']  for r in results]):.4f}")
print(f"Jaccard : {np.mean([r['jaccard'] for r in results]):.4f}")