# -*- coding: utf-8 -*-
"""Untitled53.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VLFGpNvwWjErTuzIbC44YwwpIKJDierL
"""

pip install transformers datasets peft accelerate bitsandbytes

pip install datasets transformers

from datasets import load_dataset

dataset = load_dataset("suayptalha/Poetry-Foundation-Poems")

# Preview raw data
print(dataset)
print(dataset['train'][6])  # Example with tags
# Output:
# {'Title': 'Invisible Fish',
#  'Poem': 'Invisible fish swim this ghost ocean...',
#  'Poet': 'Joy Harjo',
#  'Tags': 'Living,Time & Brevity,Nature,Seas, Rivers, & Streams'}

# ============================================
# STEP 3: Convert to [INST] training format
# ============================================
def convert_to_instruction_format(example):
    poem = example['Poem']
    tags = example['Tags']
    title = example['Title']

    # Handle rows with null/missing tags
    if tags and tags.strip():
        # Tags exist → use first tag as topic
        first_tag = tags.split(',')[0].strip()
        instruction = f"Write a poem about {first_tag}"
    elif title and title.strip():
        # No tags → use title as hint
        instruction = f"Write a poem titled '{title}'"
    else:
        # Fallback
        instruction = "Write a poem"

    # Format in LLaMA 2 [INST] style
    formatted = f"<s>[INST] {instruction} [/INST] {poem.strip()} </s>"

    return {"text": formatted}

# Apply conversion to full dataset
formatted_dataset = dataset['train'].map(convert_to_instruction_format)

# ============================================
# STEP 4: Filter out bad/empty rows
# ============================================
formatted_dataset = formatted_dataset.filter(
    lambda x: x['text'] is not None and len(x['text']) > 100
)

print(f"Total usable examples: {len(formatted_dataset)}")
# Expected: ~13,800+

# ============================================
# STEP 5: Preview a few examples
# ============================================
for i in [6, 7, 20]:
    print("---")
    print(formatted_dataset[i]['text'][:300])

# ============================================
# STEP 6: Save as JSONL for training
# ============================================
import json

with open("poetry_training.jsonl", "w") as f:
    for example in formatted_dataset:
        json.dump({"text": example["text"]}, f)
        f.write("\n")

print("✅ Saved to poetry_training.jsonl")
print(f"Total training examples: {len(formatted_dataset)}")

import json
import re

def clean_text(text):
    # Remove \r characters
    text = text.replace('\r', '')
    # Collapse multiple newlines into one
    text = re.sub(r'\n{3,}', '\n\n', text)
    # Remove excessive spaces/tabs
    text = re.sub(r'[ \t]{2,}', ' ', text)
    # Clean up messy title instructions like "Write a poem titled '\n    Title\n'"
    text = re.sub(r"titled '\s+(.+?)\s+'", lambda m: f"titled '{m.group(1).strip()}'", text)
    return text.strip()

cleaned = []
skipped = 0

with open("poetry_training.jsonl") as f:
    for line in f:
        row = json.loads(line)
        text = clean_text(row['text'])

        # Skip if poem body is too short after cleaning
        poem_body = text.split("[/INST]")[-1].replace("</s>", "").strip()
        if len(poem_body) < 20:
            skipped += 1
            continue

        cleaned.append({"text": text})

# Save cleaned version
with open("poetry_training_clean.jsonl", "w") as f:
    for row in cleaned:
        json.dump(row, f)
        f.write("\n")

print(f"✅ Cleaned rows saved : {len(cleaned)}")
print(f"⚠️  Skipped (too short): {skipped}")

from datasets import load_dataset

# This has 16,000 real diverse human questions across many topics
# We'll use the QUESTIONS only, then write our own poetry-bot refusals
dataset = load_dataset("mrfakename/refusal-xl", split="train")
print(dataset[0])
# {'input': 'Explain quantum mechanics', 'output': 'I cannot do that...'}
# We only want the 'input' column — real human questions

import json, random

# Load the real human questions
dataset = load_dataset("mrfakename/refusal-xl", split="train")

# Varied poetry-bot refusal responses
refusal_templates = [
    "I'm a poetry bot! I only write poems. Try asking: 'Write a poem about {topic}'",
    "That's outside my world — I live in poetry! Ask me to write a poem instead.",
    "I only speak in verse! Ask me to write a poem about any topic you love.",
    "Poetry is my only language. I can't help with that, but I can write you a beautiful poem!",
    "I'm not able to help with that — but I can craft a poem on any topic. What shall I write about?",
    "My heart only knows poetry. Ask me for a poem about love, nature, stars — anything!",
    "Sorry, I only write poetry. Try: 'Write me a poem about {topic}'",
]

topics = ["love", "nature", "stars", "rain", "hope", "the sea", "autumn", "friendship"]

refusal_examples = []

for example in dataset.select(range(5000)):  # use 5000 real questions
    question = example['input'].strip()

    # Skip if question is already poetry-related
    if any(w in question.lower() for w in ['poem', 'poetry', 'verse', 'rhyme', 'sonnet']):
        continue

    # Pick a random refusal + random topic suggestion
    template = random.choice(refusal_templates)
    topic = random.choice(topics)
    refusal = template.format(topic=topic)

    formatted = f"<s>[INST] {question} [/INST] {refusal} </s>"
    refusal_examples.append({"text": formatted})

# Save
with open("refusal_examples.jsonl", "w") as f:
    for r in refusal_examples:
        json.dump(r, f)
        f.write("\n")

print(f"✅ Generated {len(refusal_examples)} refusal examples")

import json
import random

# ============================================
# STEP 1: Load both files
# ============================================
poetry_examples = []
refusal_examples = []

# Load poetry file
with open("poetry_training_clean.jsonl", "r") as f:
    for line in f:
        line = line.strip()
        if line:
            poetry_examples.append(json.loads(line))

# Load refusal file
with open("refusal_examples.jsonl", "r") as f:
    for line in f:
        line = line.strip()
        if line:
            refusal_examples.append(json.loads(line))

print(f"Poetry examples  : {len(poetry_examples)}")
print(f"Refusal examples : {len(refusal_examples)}")

# ============================================
# STEP 2: Check ratio before merging
# ============================================
total = len(poetry_examples) + len(refusal_examples)
refusal_pct = (len(refusal_examples) / total) * 100

print(f"\nTotal            : {total}")
print(f"Refusal %        : {refusal_pct:.1f}%")

# If refusals are more than 15%, trim them down
MAX_REFUSAL_PCT = 0.13  # keep at 13%
max_refusals = int(len(poetry_examples) * MAX_REFUSAL_PCT / (1 - MAX_REFUSAL_PCT))

if len(refusal_examples) > max_refusals:
    print(f"\n⚠️  Too many refusals! Trimming to {max_refusals}")
    random.shuffle(refusal_examples)
    refusal_examples = refusal_examples[:max_refusals]

# ============================================
# STEP 3: Merge and shuffle
# ============================================
combined = poetry_examples + refusal_examples

# Shuffle so refusals are spread throughout
# (not all bunched at the end)
random.seed(42)
random.shuffle(combined)

print(f"\nFinal combined   : {len(combined)}")
print(f"Poetry           : {len(poetry_examples)}")
print(f"Refusals         : {len(refusal_examples)}")

# ============================================
# STEP 4: Save merged file
# ============================================
with open("combined_training.jsonl", "w") as f:
    for example in combined:
        json.dump(example, f)
        f.write("\n")

print("\n✅ Saved to combined_training.jsonl")

# ============================================
# STEP 5: Quick sanity check
# ============================================
print("\n--- 3 Random Samples ---")
for sample in random.sample(combined, 3):
    print(sample['text'][:200])
    print("---")

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

model_name = "Qwen/Qwen2.5-1.5B-Instruct"

# 4-bit quantization — fits easily in free Colab
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)

tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto"
)

print("✅ Qwen2.5-1.5B-Instruct loaded!")
print(f"Device: {next(model.parameters()).device}")

from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

# Required when using 4-bit quantization
model = prepare_model_for_kbit_training(model)

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],  # works for Qwen2.5
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

from datasets import load_dataset
from transformers import DataCollatorForLanguageModeling

dataset = load_dataset("json", data_files="combined_training.jsonl")

# ✅ Use only 5000 examples instead of 15000
# For a poetry bot this is MORE than enough
dataset_subset = dataset["train"].shuffle(seed=42).select(range(5000))

def tokenize(example):
    result = tokenizer(
        example["text"],
        truncation=True,
        max_length=256,
        padding="max_length"
    )
    result["labels"] = result["input_ids"].copy()
    return result

tokenized_dataset = dataset_subset.map(
    tokenize,
    batched=True,
    batch_size=1000,
    remove_columns=["text"]
)

tokenized_dataset = tokenized_dataset.train_test_split(test_size=0.05, seed=42)

print(f"✅ Train : {len(tokenized_dataset['train'])}")
print(f"✅ Eval  : {len(tokenized_dataset['test'])}")

from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="./poetry-tinyllama",

    per_device_train_batch_size=8,
    gradient_accumulation_steps=2,

    # ✅ Reduced from 3 → 2 epochs
    num_train_epochs=2,
    learning_rate=2e-4,

    fp16=True,
    optim="paged_adamw_8bit",
    group_by_length=True,
    dataloader_num_workers=2,

    logging_steps=25,
    save_strategy="epoch",
    save_total_limit=2,
    eval_strategy="epoch",
    load_best_model_at_end=True,

    warmup_steps=50,
    lr_scheduler_type="cosine",
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
    data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False)
)

print("🚀 Starting training...")
trainer.train()
print("✅ Training complete!")

from transformers import pipeline
import torch

pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=150,
    temperature=0.7,
    do_sample=True,
    repetition_penalty=1.2
)

def ask_bot(question):
    # Qwen2.5 uses ChatML format
    prompt = f"<|im_start|>user\n{question}<|im_end|>\n<|im_start|>assistant\n"
    output = pipe(prompt)[0]['generated_text']
    response = output.split("<|im_start|>assistant")[-1].strip()
    print(f"User : {question}")
    print(f"Bot  : {response}")
    print("-" * 50)

# ✅ Test 1 — should write a poem
ask_bot("Write a poem about rain")

# ✅ Test 2 — should write a poem
ask_bot("Write a poem about love")

# ✅ Test 3 — should REFUSE
ask_bot("What is machine learning?")

# ✅ Test 4 — should REFUSE
ask_bot("Explain Python programming")

# ✅ Test 5 — should REFUSE
ask_bot("What is 2 + 2?")

# Save LoRA adapter + tokenizer
model.save_pretrained("./poetry-qwen2.5")
tokenizer.save_pretrained("./poetry-qwen2.5")
print("✅ Model saved!")